name: Python Tests and Linting

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  deploy-ghDocs:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material mkdocstrings-python

    - name: Deploy to GitHub Pages
      run: |
        mkdocs gh-deploy --force
        
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies for testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Run unit tests with coverage
      - name: Run tests with coverage
        run: pytest --cov=. tests/

      # Run linting with Super-Linter
      - name: Linting with Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
